services:
  homeassistant:
    build: .
    volumes:
      - ./dev/ha-config:/config
      - ./custom_components:/config/custom_components:ro
    ports:
      - "8123:8123"
    restart: on-failure
    environment:
      TZ: UTC

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./dev/prometheus:/etc/prometheus:ro
    restart: on-failure

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    restart: on-failure
